// HSK 1 + bonus (171 slov) — zjednodušené znaky + pinyin s tóny + čeština
// Tvoje známá slova jsou na začátku: 我 你 我们 咖啡 妈妈 爸爸
const WORDS = [
{id:1,hz:"我",py:"wǒ",cz:"já",cat:"lidé"},
{id:2,hz:"你",py:"nǐ",cz:"ty",cat:"lidé"},
{id:3,hz:"我们",py:"wǒmen",cz:"my",cat:"lidé"},
{id:4,hz:"你们",py:"nǐmen",cz:"vy",cat:"lidé"},
{id:5,hz:"他",py:"tā",cz:"on",cat:"lidé"},
{id:6,hz:"她",py:"tā",cz:"ona",cat:"lidé"},
{id:7,hz:"他们",py:"tāmen",cz:"oni",cat:"lidé"},
{id:8,hz:"妈妈",py:"māma",cz:"máma",cat:"rodina"},
{id:9,hz:"爸爸",py:"bàba",cz:"táta",cat:"rodina"},
{id:10,hz:"儿子",py:"érzi",cz:"syn",cat:"rodina"},
{id:11,hz:"女儿",py:"nǚ'ér",cz:"dcera",cat:"rodina"},
{id:12,hz:"哥哥",py:"gēge",cz:"starší bratr",cat:"rodina"},
{id:13,hz:"姐姐",py:"jiějie",cz:"starší sestra",cat:"rodina"},
{id:14,hz:"弟弟",py:"dìdi",cz:"mladší bratr",cat:"rodina"},
{id:15,hz:"妹妹",py:"mèimei",cz:"mladší sestra",cat:"rodina"},
{id:16,hz:"丈夫",py:"zhàngfu",cz:"manžel",cat:"rodina"},
{id:17,hz:"妻子",py:"qīzi",cz:"manželka",cat:"rodina"},
{id:18,hz:"孩子",py:"háizi",cz:"dítě",cat:"rodina"},
{id:19,hz:"人",py:"rén",cz:"člověk",cat:"lidé"},
{id:20,hz:"朋友",py:"péngyou",cz:"kamarád",cat:"lidé"},
{id:21,hz:"同学",py:"tóngxué",cz:"spolužák",cat:"škola"},
{id:22,hz:"先生",py:"xiānsheng",cz:"pan",cat:"lidé"},
{id:23,hz:"小姐",py:"xiǎojie",cz:"slečna",cat:"lidé"},
{id:24,hz:"名字",py:"míngzi",cz:"jméno",cat:"základy"},
{id:25,hz:"家",py:"jiā",cz:"domov / rodina",cat:"rodina"},
{id:26,hz:"咖啡",py:"kāfēi",cz:"káva",cat:"jídlo"},
{id:27,hz:"茶",py:"chá",cz:"čaj",cat:"jídlo"},
{id:28,hz:"水",py:"shuǐ",cz:"voda",cat:"jídlo"},
{id:29,hz:"米饭",py:"mǐfàn",cz:"vařená rýže",cat:"jídlo"},
{id:30,hz:"菜",py:"cài",cz:"jídlo / chod",cat:"jídlo"},
{id:31,hz:"水果",py:"shuǐguǒ",cz:"ovoce",cat:"jídlo"},
{id:32,hz:"苹果",py:"píngguǒ",cz:"jablko",cat:"jídlo"},
{id:33,hz:"吃",py:"chī",cz:"jíst",cat:"slovesa"},
{id:34,hz:"喝",py:"hē",cz:"pít",cat:"slovesa"},
{id:35,hz:"一",py:"yī",cz:"jedna",cat:"čísla"},
{id:36,hz:"二",py:"èr",cz:"dva",cat:"čísla"},
{id:37,hz:"三",py:"sān",cz:"tři",cat:"čísla"},
{id:38,hz:"四",py:"sì",cz:"čtyři",cat:"čísla"},
{id:39,hz:"五",py:"wǔ",cz:"pět",cat:"čísla"},
{id:40,hz:"六",py:"liù",cz:"šest",cat:"čísla"},
{id:41,hz:"七",py:"qī",cz:"sedm",cat:"čísla"},
{id:42,hz:"八",py:"bā",cz:"osm",cat:"čísla"},
{id:43,hz:"九",py:"jiǔ",cz:"devět",cat:"čísla"},
{id:44,hz:"十",py:"shí",cz:"deset",cat:"čísla"},
{id:45,hz:"零",py:"líng",cz:"nula",cat:"čísla"},
{id:46,hz:"个",py:"gè",cz:"kus (měrové slovo)",cat:"gramatika"},
{id:47,hz:"岁",py:"suì",cz:"let (věk)",cat:"čas"},
{id:48,hz:"本",py:"běn",cz:"měrové slovo pro knihy",cat:"gramatika"},
{id:49,hz:"些",py:"xiē",cz:"nějaké / trochu",cat:"gramatika"},
{id:50,hz:"块",py:"kuài",cz:"kus / yuan (hovorově)",cat:"peníze"},
{id:51,hz:"钱",py:"qián",cz:"peníze",cat:"peníze"},
{id:52,hz:"今天",py:"jīntiān",cz:"dnes",cat:"čas"},
{id:53,hz:"明天",py:"míngtiān",cz:"zítra",cat:"čas"},
{id:54,hz:"昨天",py:"zuótiān",cz:"včera",cat:"čas"},
{id:55,hz:"去年",py:"qùnián",cz:"loni",cat:"čas"},
{id:56,hz:"年",py:"nián",cz:"rok",cat:"čas"},
{id:57,hz:"月",py:"yuè",cz:"měsíc",cat:"čas"},
{id:58,hz:"号",py:"hào",cz:"číslo / den v měsíci",cat:"čas"},
{id:59,hz:"星期",py:"xīngqī",cz:"týden",cat:"čas"},
{id:60,hz:"点",py:"diǎn",cz:"hodina / bod",cat:"čas"},
{id:61,hz:"分钟",py:"fēnzhōng",cz:"minuta",cat:"čas"},
{id:62,hz:"现在",py:"xiànzài",cz:"teď",cat:"čas"},
{id:63,hz:"时候",py:"shíhou",cz:"čas / když",cat:"čas"},
{id:64,hz:"上午",py:"shàngwǔ",cz:"dopoledne",cat:"čas"},
{id:65,hz:"中午",py:"zhōngwǔ",cz:"poledne",cat:"čas"},
{id:66,hz:"下午",py:"xiàwǔ",cz:"odpoledne",cat:"čas"},
{id:67,hz:"是",py:"shì",cz:"být (je)",cat:"slovesa"},
{id:68,hz:"有",py:"yǒu",cz:"mít",cat:"slovesa"},
{id:69,hz:"在",py:"zài",cz:"být někde / v",cat:"slovesa"},
{id:70,hz:"要",py:"yào",cz:"chtít / muset / bude",cat:"slovesa"},
{id:71,hz:"会",py:"huì",cz:"umět / bude",cat:"slovesa"},
{id:72,hz:"能",py:"néng",cz:"moci",cat:"slovesa"},
{id:73,hz:"可以",py:"kěyǐ",cz:"smět / je možné",cat:"slovesa"},
{id:74,hz:"想",py:"xiǎng",cz:"chtít / myslet",cat:"slovesa"},
{id:75,hz:"喜欢",py:"xǐhuan",cz:"mít rád",cat:"slovesa"},
{id:76,hz:"爱",py:"ài",cz:"milovat",cat:"slovesa"},
{id:77,hz:"说",py:"shuō",cz:"říkat / mluvit",cat:"slovesa"},
{id:78,hz:"读",py:"dú",cz:"číst nahlas",cat:"slovesa"},
{id:79,hz:"看",py:"kàn",cz:"dívat se",cat:"slovesa"},
{id:80,hz:"看见",py:"kànjiàn",cz:"uvidět / spatřit",cat:"slovesa"},
{id:81,hz:"听",py:"tīng",cz:"poslouchat",cat:"slovesa"},
{id:82,hz:"写",py:"xiě",cz:"psát",cat:"slovesa"},
{id:83,hz:"叫",py:"jiào",cz:"jmenovat se / volat",cat:"slovesa"},
{id:84,hz:"来",py:"lái",cz:"přijít",cat:"slovesa"},
{id:85,hz:"去",py:"qù",cz:"jít",cat:"slovesa"},
{id:86,hz:"回",py:"huí",cz:"vrátit se",cat:"slovesa"},
{id:87,hz:"住",py:"zhù",cz:"bydlet",cat:"slovesa"},
{id:88,hz:"买",py:"mǎi",cz:"koupit",cat:"slovesa"},
{id:89,hz:"开",py:"kāi",cz:"otevřít / zapnout / řídit",cat:"slovesa"},
{id:90,hz:"坐",py:"zuò",cz:"sedět / jet (dopravou)",cat:"slovesa"},
{id:91,hz:"做",py:"zuò",cz:"dělat",cat:"slovesa"},
{id:92,hz:"认识",py:"rènshi",cz:"znát / poznat",cat:"slovesa"},
{id:93,hz:"睡觉",py:"shuìjiào",cz:"spát",cat:"slovesa"},
{id:94,hz:"打电话",py:"dǎ diànhuà",cz:"telefonovat",cat:"slovesa"},
{id:95,hz:"下雨",py:"xiàyǔ",cz:"prší",cat:"příroda"},
{id:96,hz:"学习",py:"xuéxí",cz:"učit se",cat:"škola"},
{id:97,hz:"学校",py:"xuéxiào",cz:"škola",cat:"škola"},
{id:98,hz:"老师",py:"lǎoshī",cz:"učitel",cat:"škola"},
{id:99,hz:"学生",py:"xuéshēng",cz:"student",cat:"škola"},
{id:100,hz:"汉语",py:"Hànyǔ",cz:"čínština",cat:"škola"},
{id:101,hz:"字",py:"zì",cz:"znak",cat:"škola"},
{id:102,hz:"书",py:"shū",cz:"kniha",cat:"škola"},
{id:103,hz:"上班",py:"shàngbān",cz:"jít do práce",cat:"práce"},
{id:104,hz:"下班",py:"xiàbān",cz:"jít z práce",cat:"práce"},
{id:105,hz:"工作",py:"gōngzuò",cz:"práce / pracovat",cat:"práce"},
{id:106,hz:"医生",py:"yīshēng",cz:"lékař",cat:"práce"},
{id:107,hz:"医院",py:"yīyuàn",cz:"nemocnice",cat:"místa"},
{id:108,hz:"商店",py:"shāngdiàn",cz:"obchod",cat:"místa"},
{id:109,hz:"饭店",py:"fàndiàn",cz:"restaurace",cat:"místa"},
{id:110,hz:"北京",py:"Běijīng",cz:"Peking",cat:"místa"},
{id:111,hz:"中国",py:"Zhōngguó",cz:"Čína",cat:"místa"},
{id:112,hz:"桌子",py:"zhuōzi",cz:"stůl",cat:"věci"},
{id:113,hz:"椅子",py:"yǐzi",cz:"židle",cat:"věci"},
{id:114,hz:"电脑",py:"diànnǎo",cz:"počítač",cat:"věci"},
{id:115,hz:"电视",py:"diànshì",cz:"televize",cat:"věci"},
{id:116,hz:"电影",py:"diànyǐng",cz:"film",cat:"věci"},
{id:117,hz:"电话",py:"diànhuà",cz:"telefon",cat:"věci"},
{id:118,hz:"手机",py:"shǒujī",cz:"mobil",cat:"věci"},
{id:119,hz:"衣服",py:"yīfu",cz:"oblečení",cat:"věci"},
{id:120,hz:"杯子",py:"bēizi",cz:"hrnek / sklenice",cat:"věci"},
{id:121,hz:"东西",py:"dōngxi",cz:"věc",cat:"věci"},
{id:122,hz:"出租车",py:"chūzūchē",cz:"taxi",cat:"doprava"},
{id:123,hz:"飞机",py:"fēijī",cz:"letadlo",cat:"doprava"},
{id:124,hz:"狗",py:"gǒu",cz:"pes",cat:"zvířata"},
{id:125,hz:"猫",py:"māo",cz:"kočka",cat:"zvířata"},
{id:126,hz:"天气",py:"tiānqì",cz:"počasí",cat:"příroda"},
{id:127,hz:"冷",py:"lěng",cz:"studený",cat:"popis"},
{id:128,hz:"大",py:"dà",cz:"velký",cat:"popis"},
{id:129,hz:"小",py:"xiǎo",cz:"malý",cat:"popis"},
{id:130,hz:"多",py:"duō",cz:"mnoho",cat:"popis"},
{id:131,hz:"少",py:"shǎo",cz:"málo",cat:"popis"},
{id:132,hz:"好",py:"hǎo",cz:"dobrý",cat:"popis"},
{id:133,hz:"漂亮",py:"piàoliang",cz:"hezký",cat:"popis"},
{id:134,hz:"高兴",py:"gāoxìng",cz:"rád / šťastný",cat:"popis"},
{id:135,hz:"不",py:"bù",cz:"ne (zápor)",cat:"gramatika"},
{id:136,hz:"没",py:"méi",cz:"ne / nemít",cat:"gramatika"},
{id:137,hz:"很",py:"hěn",cz:"velmi",cat:"gramatika"},
{id:138,hz:"太",py:"tài",cz:"příliš",cat:"gramatika"},
{id:139,hz:"都",py:"dōu",cz:"všichni",cat:"gramatika"},
{id:140,hz:"和",py:"hé",cz:"a / s",cat:"gramatika"},
{id:141,hz:"的",py:"de",cz:"přivlastňovací částice",cat:"gramatika"},
{id:142,hz:"了",py:"le",cz:"částice změny / hotovo",cat:"gramatika"},
{id:143,hz:"吗",py:"ma",cz:"otázková částice",cat:"gramatika"},
{id:144,hz:"呢",py:"ne",cz:"a co…? (částice)",cat:"gramatika"},
{id:145,hz:"这",py:"zhè",cz:"tento",cat:"ukazovací"},
{id:146,hz:"那",py:"nà",cz:"tamten",cat:"ukazovací"},
{id:147,hz:"这儿",py:"zhèr",cz:"tady",cat:"ukazovací"},
{id:148,hz:"那儿",py:"nàr",cz:"tam",cat:"ukazovací"},
{id:149,hz:"哪",py:"nǎ",cz:"který",cat:"otázky"},
{id:150,hz:"哪儿",py:"nǎr",cz:"kde",cat:"otázky"},
{id:151,hz:"谁",py:"shéi",cz:"kdo",cat:"otázky"},
{id:152,hz:"什么",py:"shénme",cz:"co",cat:"otázky"},
{id:153,hz:"多少",py:"duōshao",cz:"kolik",cat:"otázky"},
{id:154,hz:"几",py:"jǐ",cz:"kolik (málo)",cat:"otázky"},
{id:155,hz:"怎么",py:"zěnme",cz:"jak",cat:"otázky"},
{id:156,hz:"怎么样",py:"zěnmeyàng",cz:"jaké to je",cat:"otázky"},
{id:157,hz:"上",py:"shàng",cz:"na / nahoru",cat:"místo"},
{id:158,hz:"下",py:"xià",cz:"dolů / pod",cat:"místo"},
{id:159,hz:"里",py:"lǐ",cz:"uvnitř",cat:"místo"},
{id:160,hz:"前面",py:"qiánmian",cz:"vpředu / před",cat:"místo"},
{id:161,hz:"后面",py:"hòumian",cz:"vzadu / za",cat:"místo"},
{id:162,hz:"谢谢",py:"xièxie",cz:"děkuji",cat:"zdvořilost"},
{id:163,hz:"对不起",py:"duìbuqǐ",cz:"promiň",cat:"zdvořilost"},
{id:164,hz:"没关系",py:"méi guānxi",cz:"to nevadí",cat:"zdvořilost"},
{id:165,hz:"不客气",py:"bú kèqi",cz:"není zač",cat:"zdvořilost"},
{id:166,hz:"再见",py:"zàijiàn",cz:"na shledanou",cat:"zdvořilost"},
{id:167,hz:"喂",py:"wèi",cz:"haló (do telefonu)",cat:"zdvořilost"},
{id:168,hz:"让",py:"ràng",cz:"nechat / dovolit",cat:"slovesa"},
{id:169,hz:"一点儿",py:"yìdiǎnr",cz:"trochu",cat:"gramatika"},
{id:170,hz:"见",py:"jiàn",cz:"vidět / setkat se",cat:"slovesa"},
{id:171,hz:"饭",py:"fàn",cz:"jídlo / vařená rýže",cat:"jídlo"}
];

// Věty na skládání — jen ze slov výše. tokens = dílky na klikání.
const SENTENCES = [
{tokens:["我","喝","咖啡"],full:"我喝咖啡。",py:"Wǒ hē kāfēi.",cz:"Piju kávu."},
{tokens:["我","喝","茶"],full:"我喝茶。",py:"Wǒ hē chá.",cz:"Piju čaj."},
{tokens:["我","喝","水"],full:"我喝水。",py:"Wǒ hē shuǐ.",cz:"Piju vodu."},
{tokens:["我","吃","米饭"],full:"我吃米饭。",py:"Wǒ chī mǐfàn.",cz:"Jím rýži."},
{tokens:["我","吃","苹果"],full:"我吃苹果。",py:"Wǒ chī píngguǒ.",cz:"Jím jablko."},
{tokens:["我","爱","妈妈"],full:"我爱妈妈。",py:"Wǒ ài māma.",cz:"Miluju mámu."},
{tokens:["我","爱","爸爸"],full:"我爱爸爸。",py:"Wǒ ài bàba.",cz:"Miluju tátu."},
{tokens:["你","叫","什么","名字"],full:"你叫什么名字？",py:"Nǐ jiào shénme míngzi?",cz:"Jak se jmenuješ?"},
{tokens:["我","是","学生"],full:"我是学生。",py:"Wǒ shì xuéshēng.",cz:"Jsem student."},
{tokens:["这","是","我","朋友"],full:"这是我朋友。",py:"Zhè shì wǒ péngyou.",cz:"To je můj kamarád."},
{tokens:["我","喜欢","猫"],full:"我喜欢猫。",py:"Wǒ xǐhuan māo.",cz:"Mám rád kočky."},
{tokens:["我","喜欢","狗"],full:"我喜欢狗。",py:"Wǒ xǐhuan gǒu.",cz:"Mám rád psy."},
{tokens:["我","在","北京"],full:"我在北京。",py:"Wǒ zài Běijīng.",cz:"Jsem v Pekingu."},
{tokens:["现在","下雨"],full:"现在下雨。",py:"Xiànzài xiàyǔ.",cz:"Teď prší."},
{tokens:["天气","很","好"],full:"天气很好。",py:"Tiānqì hěn hǎo.",cz:"Počasí je moc hezké."},
{tokens:["谢谢","你"],full:"谢谢你。",py:"Xièxie nǐ.",cz:"Děkuju ti."},
{tokens:["对不起"],full:"对不起。",py:"Duìbuqǐ.",cz:"Promiň."},
{tokens:["没关系"],full:"没关系。",py:"Méi guānxi.",cz:"To nevadí."},
{tokens:["你","是","学生","吗"],full:"你是学生吗？",py:"Nǐ shì xuéshēng ma?",cz:"Jsi student?"},
{tokens:["我","买","苹果"],full:"我买苹果。",py:"Wǒ mǎi píngguǒ.",cz:"Kupuju jablka."},
{tokens:["我","看","电影"],full:"我看电影。",py:"Wǒ kàn diànyǐng.",cz:"Dívám se na film."},
{tokens:["我","学习","汉语"],full:"我学习汉语。",py:"Wǒ xuéxí Hànyǔ.",cz:"Učím se čínsky."},
{tokens:["我","住","在","中国"],full:"我住在中国。",py:"Wǒ zhù zài Zhōngguó.",cz:"Bydlím v Číně."},
{tokens:["明天","见"],full:"明天见。",py:"Míngtiān jiàn.",cz:"Uvidíme se zítra."},
{tokens:["昨天","我","看","电视"],full:"昨天我看电视。",py:"Zuótiān wǒ kàn diànshì.",cz:"Včera jsem koukal na televizi."},
{tokens:["我","有","三","个","苹果"],full:"我有三个苹果。",py:"Wǒ yǒu sān gè píngguǒ.",cz:"Mám tři jablka."},
{tokens:["你","喜欢","喝","茶","吗"],full:"你喜欢喝茶吗？",py:"Nǐ xǐhuan hē chá ma?",cz:"Máš rád čaj?"},
{tokens:["我","在","饭店","吃","饭"],full:"我在饭店吃饭。",py:"Wǒ zài fàndiàn chī fàn.",cz:"Jím v restauraci."},
{tokens:["我","去","学校"],full:"我去学校。",py:"Wǒ qù xuéxiào.",cz:"Jdu do školy."},
{tokens:["我","回","家"],full:"我回家。",py:"Wǒ huí jiā.",cz:"Jdu domů."}
];
