// HSK 2 (138 nových slov) — zjednodušené znaky + pinyin s tóny + čeština
// HSK 1 balík je ve words.js (id 1-171). Tady id 1001+. Pravidlo: jen APPEND, nikdy neměnit pořadí (audio/indexy).
const WORDS2 = [
{id:1001,hz:"吧",py:"ba",cz:"částice (návrh / souhlas)",cat:"gramatika",hsk:2},
{id:1002,hz:"白",py:"bái",cz:"bílý",cat:"popis",hsk:2},
{id:1003,hz:"百",py:"bǎi",cz:"sto",cat:"čísla",hsk:2},
{id:1004,hz:"帮助",py:"bāngzhù",cz:"pomáhat / pomoc",cat:"slovesa",hsk:2},
{id:1005,hz:"报纸",py:"bàozhǐ",cz:"noviny",cat:"věci",hsk:2},
{id:1006,hz:"比",py:"bǐ",cz:"než (srovnání)",cat:"gramatika",hsk:2},
{id:1007,hz:"便宜",py:"piányi",cz:"levný",cat:"popis",hsk:2},
{id:1008,hz:"别",py:"bié",cz:"ne- (zákaz)",cat:"gramatika",hsk:2},
{id:1009,hz:"唱歌",py:"chànggē",cz:"zpívat",cat:"slovesa",hsk:2},
{id:1010,hz:"出",py:"chū",cz:"vyjít / vycestovat",cat:"slovesa",hsk:2},
{id:1011,hz:"穿",py:"chuān",cz:"nosit (oblečení)",cat:"slovesa",hsk:2},
{id:1012,hz:"船",py:"chuán",cz:"loď",cat:"doprava",hsk:2},
{id:1013,hz:"次",py:"cì",cz:"-krát",cat:"gramatika",hsk:2},
{id:1014,hz:"从",py:"cóng",cz:"z / od",cat:"gramatika",hsk:2},
{id:1015,hz:"错",py:"cuò",cz:"chyba / špatný",cat:"popis",hsk:2},
{id:1016,hz:"打篮球",py:"dǎlánqiú",cz:"hrát basketbal",cat:"sport",hsk:2},
{id:1017,hz:"大家",py:"dàjiā",cz:"všichni",cat:"lidé",hsk:2},
{id:1018,hz:"但是",py:"dànshì",cz:"ale",cat:"gramatika",hsk:2},
{id:1019,hz:"到",py:"dào",cz:"dorazit / do",cat:"slovesa",hsk:2},
{id:1020,hz:"得",py:"de",cz:"slovesná částice / muset",cat:"gramatika",hsk:2},
{id:1021,hz:"第一",py:"dìyī",cz:"první",cat:"čísla",hsk:2},
{id:1022,hz:"懂",py:"dǒng",cz:"rozumět",cat:"slovesa",hsk:2},
{id:1023,hz:"房间",py:"fángjiān",cz:"pokoj",cat:"místa",hsk:2},
{id:1024,hz:"非常",py:"fēicháng",cz:"velmi / extrémně",cat:"gramatika",hsk:2},
{id:1025,hz:"服务员",py:"fúwùyuán",cz:"číšník / obsluha",cat:"lidé",hsk:2},
{id:1026,hz:"高",py:"gāo",cz:"vysoký",cat:"popis",hsk:2},
{id:1027,hz:"告诉",py:"gàosu",cz:"říct (někomu)",cat:"slovesa",hsk:2},
{id:1028,hz:"给",py:"gěi",cz:"dát / pro",cat:"slovesa",hsk:2},
{id:1029,hz:"公共汽车",py:"gōnggòngqìchē",cz:"autobus",cat:"doprava",hsk:2},
{id:1030,hz:"公斤",py:"gōngjīn",cz:"kilogram",cat:"čísla",hsk:2},
{id:1031,hz:"公司",py:"gōngsī",cz:"firma",cat:"práce",hsk:2},
{id:1032,hz:"贵",py:"guì",cz:"drahý",cat:"popis",hsk:2},
{id:1033,hz:"还",py:"hái",cz:"ještě / také",cat:"gramatika",hsk:2},
{id:1034,hz:"好吃",py:"hǎochī",cz:"chutný",cat:"jídlo",hsk:2},
{id:1035,hz:"黑",py:"hēi",cz:"černý",cat:"popis",hsk:2},
{id:1036,hz:"红",py:"hóng",cz:"červený",cat:"popis",hsk:2},
{id:1037,hz:"欢迎",py:"huānyíng",cz:"vítat",cat:"zdvořilost",hsk:2},
{id:1038,hz:"回答",py:"huídá",cz:"odpovědět",cat:"slovesa",hsk:2},
{id:1039,hz:"机场",py:"jīchǎng",cz:"letiště",cat:"místa",hsk:2},
{id:1040,hz:"鸡蛋",py:"jīdàn",cz:"vejce",cat:"jídlo",hsk:2},
{id:1041,hz:"件",py:"jiàn",cz:"kus (oblečení)",cat:"gramatika",hsk:2},
{id:1042,hz:"教室",py:"jiàoshì",cz:"třída / učebna",cat:"škola",hsk:2},
{id:1043,hz:"介绍",py:"jièshào",cz:"představit",cat:"slovesa",hsk:2},
{id:1044,hz:"近",py:"jìn",cz:"blízko",cat:"místo",hsk:2},
{id:1045,hz:"进",py:"jìn",cz:"vejít / vstoupit",cat:"slovesa",hsk:2},
{id:1046,hz:"就",py:"jiù",cz:"právě / pak",cat:"gramatika",hsk:2},
{id:1047,hz:"觉得",py:"juéde",cz:"myslet si / připadat",cat:"slovesa",hsk:2},
{id:1048,hz:"开始",py:"kāishǐ",cz:"začít",cat:"slovesa",hsk:2},
{id:1049,hz:"考试",py:"kǎoshì",cz:"zkouška",cat:"škola",hsk:2},
{id:1050,hz:"可能",py:"kěnéng",cz:"možná / moci",cat:"gramatika",hsk:2},
{id:1051,hz:"课",py:"kè",cz:"hodina / lekce",cat:"škola",hsk:2},
{id:1052,hz:"快",py:"kuài",cz:"rychlý",cat:"popis",hsk:2},
{id:1053,hz:"快乐",py:"kuàilè",cz:"šťastný / veselý",cat:"popis",hsk:2},
{id:1054,hz:"累",py:"lèi",cz:"unavený",cat:"popis",hsk:2},
{id:1055,hz:"离",py:"lí",cz:"od (vzdálenost)",cat:"gramatika",hsk:2},
{id:1056,hz:"两",py:"liǎng",cz:"dva (kusy)",cat:"čísla",hsk:2},
{id:1057,hz:"路",py:"lù",cz:"cesta / silnice",cat:"místa",hsk:2},
{id:1058,hz:"旅游",py:"lǚyóu",cz:"cestovat / turistika",cat:"cestování",hsk:2},
{id:1059,hz:"卖",py:"mài",cz:"prodávat",cat:"slovesa",hsk:2},
{id:1060,hz:"慢",py:"màn",cz:"pomalý",cat:"popis",hsk:2},
{id:1061,hz:"忙",py:"máng",cz:"zaneprázdněný",cat:"popis",hsk:2},
{id:1062,hz:"每",py:"měi",cz:"každý",cat:"gramatika",hsk:2},
{id:1063,hz:"门",py:"mén",cz:"dveře",cat:"věci",hsk:2},
{id:1064,hz:"男人",py:"nánrén",cz:"muž",cat:"lidé",hsk:2},
{id:1065,hz:"您",py:"nín",cz:"vy (zdvořile)",cat:"lidé",hsk:2},
{id:1066,hz:"牛奶",py:"niúnǎi",cz:"mléko",cat:"jídlo",hsk:2},
{id:1067,hz:"女人",py:"nǚrén",cz:"žena",cat:"lidé",hsk:2},
{id:1068,hz:"旁边",py:"pángbiān",cz:"vedle",cat:"místo",hsk:2},
{id:1069,hz:"跑步",py:"pǎobù",cz:"běhat",cat:"sport",hsk:2},
{id:1070,hz:"票",py:"piào",cz:"lístek",cat:"cestování",hsk:2},
{id:1071,hz:"起床",py:"qǐchuáng",cz:"vstávat",cat:"slovesa",hsk:2},
{id:1072,hz:"千",py:"qiān",cz:"tisíc",cat:"čísla",hsk:2},
{id:1073,hz:"晴",py:"qíng",cz:"jasno",cat:"příroda",hsk:2},
{id:1074,hz:"身体",py:"shēntǐ",cz:"tělo / zdraví",cat:"zdraví",hsk:2},
{id:1075,hz:"生病",py:"shēngbìng",cz:"onemocnět",cat:"zdraví",hsk:2},
{id:1076,hz:"生日",py:"shēngrì",cz:"narozeniny",cat:"čas",hsk:2},
{id:1077,hz:"时间",py:"shíjiān",cz:"čas",cat:"čas",hsk:2},
{id:1078,hz:"事情",py:"shìqing",cz:"věc / záležitost",cat:"věci",hsk:2},
{id:1079,hz:"手表",py:"shǒubiǎo",cz:"hodinky",cat:"věci",hsk:2},
{id:1080,hz:"送",py:"sòng",cz:"darovat / doprovodit",cat:"slovesa",hsk:2},
{id:1081,hz:"所以",py:"suǒyǐ",cz:"proto / takže",cat:"gramatika",hsk:2},
{id:1082,hz:"它",py:"tā",cz:"ono",cat:"lidé",hsk:2},
{id:1083,hz:"踢",py:"tī",cz:"kopnout",cat:"sport",hsk:2},
{id:1084,hz:"题",py:"tí",cz:"úkol / testová otázka",cat:"škola",hsk:2},
{id:1085,hz:"跳舞",py:"tiàowǔ",cz:"tančit",cat:"sport",hsk:2},
{id:1086,hz:"外",py:"wài",cz:"venku / vnější",cat:"místo",hsk:2},
{id:1087,hz:"完",py:"wán",cz:"dokončit",cat:"slovesa",hsk:2},
{id:1088,hz:"玩",py:"wán",cz:"hrát si / bavit se",cat:"slovesa",hsk:2},
{id:1089,hz:"晚上",py:"wǎnshang",cz:"večer",cat:"čas",hsk:2},
{id:1090,hz:"为",py:"wèi",cz:"pro / kvůli",cat:"gramatika",hsk:2},
{id:1091,hz:"问",py:"wèn",cz:"ptát se",cat:"slovesa",hsk:2},
{id:1092,hz:"问题",py:"wèntí",cz:"otázka / problém",cat:"věci",hsk:2},
{id:1093,hz:"希望",py:"xīwàng",cz:"doufat / naděje",cat:"slovesa",hsk:2},
{id:1094,hz:"洗",py:"xǐ",cz:"mýt / prát",cat:"slovesa",hsk:2},
{id:1095,hz:"西瓜",py:"xīguā",cz:"meloun",cat:"jídlo",hsk:2},
{id:1096,hz:"向",py:"xiàng",cz:"směrem k",cat:"gramatika",hsk:2},
{id:1097,hz:"小时",py:"xiǎoshí",cz:"hodina (60 min)",cat:"čas",hsk:2},
{id:1098,hz:"笑",py:"xiào",cz:"smát se",cat:"slovesa",hsk:2},
{id:1099,hz:"新",py:"xīn",cz:"nový",cat:"popis",hsk:2},
{id:1100,hz:"姓",py:"xìng",cz:"příjmení / jmenovat se",cat:"lidé",hsk:2},
{id:1101,hz:"休息",py:"xiūxi",cz:"odpočívat",cat:"slovesa",hsk:2},
{id:1102,hz:"雪",py:"xuě",cz:"sníh",cat:"příroda",hsk:2},
{id:1103,hz:"颜色",py:"yánsè",cz:"barva",cat:"popis",hsk:2},
{id:1104,hz:"眼睛",py:"yǎnjing",cz:"oči",cat:"zdraví",hsk:2},
{id:1105,hz:"羊肉",py:"yángròu",cz:"skopové",cat:"jídlo",hsk:2},
{id:1106,hz:"药",py:"yào",cz:"lék",cat:"zdraví",hsk:2},
{id:1107,hz:"也",py:"yě",cz:"také",cat:"gramatika",hsk:2},
{id:1108,hz:"一起",py:"yìqǐ",cz:"spolu",cat:"gramatika",hsk:2},
{id:1109,hz:"已经",py:"yǐjīng",cz:"už",cat:"gramatika",hsk:2},
{id:1110,hz:"意思",py:"yìsi",cz:"význam",cat:"věci",hsk:2},
{id:1111,hz:"因为",py:"yīnwèi",cz:"protože",cat:"gramatika",hsk:2},
{id:1112,hz:"阴",py:"yīn",cz:"zataženo",cat:"příroda",hsk:2},
{id:1113,hz:"游泳",py:"yóuyǒng",cz:"plavat",cat:"sport",hsk:2},
{id:1114,hz:"右边",py:"yòubian",cz:"vpravo",cat:"místo",hsk:2},
{id:1115,hz:"鱼",py:"yú",cz:"ryba",cat:"jídlo",hsk:2},
{id:1116,hz:"元",py:"yuán",cz:"yuan",cat:"peníze",hsk:2},
{id:1117,hz:"远",py:"yuǎn",cz:"daleko",cat:"místo",hsk:2},
{id:1118,hz:"运动",py:"yùndòng",cz:"sportovat / sport",cat:"sport",hsk:2},
{id:1119,hz:"再",py:"zài",cz:"znovu",cat:"gramatika",hsk:2},
{id:1120,hz:"早上",py:"zǎoshang",cz:"ráno",cat:"čas",hsk:2},
{id:1121,hz:"张",py:"zhāng",cz:"measure (ploché věci)",cat:"gramatika",hsk:2},
{id:1122,hz:"长",py:"cháng",cz:"dlouhý",cat:"popis",hsk:2},
{id:1123,hz:"找",py:"zhǎo",cz:"hledat",cat:"slovesa",hsk:2},
{id:1124,hz:"着",py:"zhe",cz:"částice (průběh)",cat:"gramatika",hsk:2},
{id:1125,hz:"真",py:"zhēn",cz:"opravdu",cat:"gramatika",hsk:2},
{id:1126,hz:"正在",py:"zhèngzài",cz:"právě (teď)",cat:"gramatika",hsk:2},
{id:1127,hz:"知道",py:"zhīdào",cz:"vědět",cat:"slovesa",hsk:2},
{id:1128,hz:"准备",py:"zhǔnbèi",cz:"připravit / připravovat",cat:"slovesa",hsk:2},
{id:1129,hz:"自行车",py:"zìxíngchē",cz:"kolo",cat:"doprava",hsk:2},
{id:1130,hz:"走",py:"zǒu",cz:"jít pěšky / odejít",cat:"slovesa",hsk:2},
{id:1131,hz:"最",py:"zuì",cz:"nej-",cat:"gramatika",hsk:2},
{id:1132,hz:"左边",py:"zuǒbian",cz:"vlevo",cat:"místo",hsk:2},
{id:1133,hz:"以前",py:"yǐqián",cz:"dříve / předtím",cat:"čas",hsk:2},
{id:1134,hz:"以后",py:"yǐhòu",cz:"potom / později",cat:"čas",hsk:2},
{id:1135,hz:"为什么",py:"wèishénme",cz:"proč",cat:"otázky",hsk:2},
{id:1136,hz:"常常",py:"chángcháng",cz:"často",cat:"čas",hsk:2},
{id:1137,hz:"上网",py:"shàngwǎng",cz:"být na internetu",cat:"věci",hsk:2},
{id:1138,hz:"一些",py:"yìxiē",cz:"nějaké / pár",cat:"gramatika",hsk:2}
];

// HSK 2 věty — jen ze slov HSK 1+2.
const SENTENCES2 = [
{tokens:["我","觉得","很","好"],full:"我觉得很好。",py:"Wǒ juéde hěn hǎo.",cz:"Myslím, že je to moc dobré.",hsk:2},
{tokens:["他","告诉","我","了"],full:"他告诉我了。",py:"Tā gàosu wǒ le.",cz:"Řekl mi to.",hsk:2},
{tokens:["我们","一起","去","吧"],full:"我们一起去吧。",py:"Wǒmen yìqǐ qù ba.",cz:"Pojďme spolu.",hsk:2},
{tokens:["你","为什么","不","去"],full:"你为什么不去？",py:"Nǐ wèishénme bú qù?",cz:"Proč nejdeš?",hsk:2},
{tokens:["我","知道","他"],full:"我知道他。",py:"Wǒ zhīdào tā.",cz:"Znám ho.",hsk:2},
{tokens:["她","非常","漂亮"],full:"她非常漂亮。",py:"Tā fēicháng piàoliang.",cz:"Je moc hezká.",hsk:2},
{tokens:["我","想","喝","牛奶"],full:"我想喝牛奶。",py:"Wǒ xiǎng hē niúnǎi.",cz:"Chci pít mléko.",hsk:2},
{tokens:["你","喜欢","吃","什么"],full:"你喜欢吃什么？",py:"Nǐ xǐhuan chī shénme?",cz:"Co rád jíš?",hsk:2},
{tokens:["我","在","准备","考试"],full:"我在准备考试。",py:"Wǒ zài zhǔnbèi kǎoshì.",cz:"Připravuju se na zkoušku.",hsk:2},
{tokens:["他","跑步","很","快"],full:"他跑步很快。",py:"Tā pǎobù hěn kuài.",cz:"Běhá moc rychle.",hsk:2},
{tokens:["我们","是","同学"],full:"我们是同学。",py:"Wǒmen shì tóngxué.",cz:"Jsme spolužáci.",hsk:2},
{tokens:["你","家","在","哪儿"],full:"你家在哪儿？",py:"Nǐ jiā zài nǎr?",cz:"Kde bydlíš?",hsk:2},
{tokens:["我","买","了","两","本","书"],full:"我买了两本书。",py:"Wǒ mǎi le liǎng běn shū.",cz:"Koupil jsem dvě knihy.",hsk:2},
{tokens:["谢谢","你","的","帮助"],full:"谢谢你的帮助。",py:"Xièxie nǐ de bāngzhù.",cz:"Děkuji za pomoc.",hsk:2},
{tokens:["今天","天气","很","好"],full:"今天天气很好。",py:"Jīntiān tiānqì hěn hǎo.",cz:"Dnes je moc hezké počasí.",hsk:2},
{tokens:["我","希望","去","中国"],full:"我希望去中国。",py:"Wǒ xīwàng qù Zhōngguó.",cz:"Doufám, že pojedu do Číny.",hsk:2},
{tokens:["他","在","左边"],full:"他在左边。",py:"Tā zài zuǒbian.",cz:"Je vlevo.",hsk:2},
{tokens:["我","喜欢","游泳"],full:"我喜欢游泳。",py:"Wǒ xǐhuan yóuyǒng.",cz:"Rád plavu.",hsk:2},
{tokens:["你","吃","什么","药"],full:"你吃什么药？",py:"Nǐ chī shénme yào?",cz:"Jaký bereš lék?",hsk:2},
{tokens:["我们","明天","见"],full:"我们明天见。",py:"Wǒmen míngtiān jiàn.",cz:"Uvidíme se zítra.",hsk:2}
];
